port module Command.GenerateApiFiles.InteropPorts exposing (fromElm, toElm)

{-| This file was generated by elm-ts-interop init. You can manually edit this file,
just avoid exposing the low-level ports to ensure that only the FromElm and ToElm types
can be sent/received by your ports.

@docs fromElm, toElm

-}

import Command.GenerateApiFiles.InteropDefinitions as InteropDefinitions
import Json.Decode as Decode
import Json.Encode as Encode
import TsJson.Decode as TsDecode
import TsJson.Encode as TsEncode


{-| -}
fromElm : InteropDefinitions.FromElm -> Cmd msg_
fromElm value =
    TsEncode.encoder InteropDefinitions.interop.fromElm
        value
        |> interopFromElm


{-| -}
toElm : Sub (Result Decode.Error InteropDefinitions.ToElm)
toElm =
    TsDecode.decoder InteropDefinitions.interop.toElm
        |> Decode.decodeValue
        |> interopToElm



-- internals - do not expose


port interopFromElm : Encode.Value -> Cmd msg_


port interopToElm : (Decode.Value -> msg) -> Sub msg
