port module InteropPorts exposing (fromElm, toElm, decodeFlags)

{-| This file was generated by elm-ts-interop init. You can manually edit this file,
just avoid exposing the low-level ports to ensure that only the FromElm and ToElm types
can be sent/received by your ports.

@docs fromElm, toElm, decodeFlags

-}

import InteropDefinitions
import Json.Decode as Decode
import Json.Encode as Encode
import TsJson.Decode as TsDecode
import TsJson.Encode as TsEncode


{-| Send a message from Elm to Typescript
-}
fromElm : InteropDefinitions.FromElm -> Cmd msg_
fromElm value =
    TsEncode.encoder InteropDefinitions.interop.fromElm value
        |> interopFromElm


{-| Receive a message from Typescript to Elm. This should only be used in Main.
Other modules should have a `toElmSubscription : InteropDefinitions.ToElm -> Maybe Msg`,
which needs to be wired up in Main
-}
toElm : Sub (Result Decode.Error InteropDefinitions.ToElm)
toElm =
    TsDecode.decoder InteropDefinitions.interop.toElm
        |> Decode.decodeValue
        |> interopToElm


{-| Decode the flags received from Typescript
-}
decodeFlags : Decode.Value -> Result Decode.Error InteropDefinitions.Flags
decodeFlags flags =
    Decode.decodeValue
        (TsDecode.decoder InteropDefinitions.interop.flags)
        flags



-- internals - do not expose


port interopFromElm : Encode.Value -> Cmd msg_


port interopToElm : (Decode.Value -> msg) -> Sub msg
